import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../src/components/Navbar'
import styles from '../styles/Home.module.css'
import { createTheme, ThemeProvider } from '@mui/material/styles';
import { green, orange } from '@mui/material/colors';
import Footer from '../src/components/Footer';
import RestuarantItem from '../src/components/RestuarantItem';
import { Grid } from '@mui/material';
import RestuarantList from '../src/components/RestuarantList';
import { GlobalProvider } from '../src/contexts/GlobalContext';

const outerTheme = createTheme({
  // palette: {
  //   primary: {
  //     main: orange[50],
  //   },
  // },
});
export default function Home() {
  return (
    <ThemeProvider theme={outerTheme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalProvider>
        <Navbar />
        <Grid container style={{ padding: '50px' }}>
          <RestuarantList />
        </Grid>
        <Footer />
      </GlobalProvider>
    </ThemeProvider>
  )
}
